### ISSUE TITLE
Please share code formatter

### ISSUE THREAD

**Issue by tubbynl** [bunq/sdk_java#103]
contributing is not workable as-is

applying standard formatting of intellij on for example ApiClient gives a full file change.

please provide the used codeformatting template in intellij somewhere

and also be consistent about Java7 or not, have the Java7 changes done on that issue and not on all issues currently pending

**Comment by OGKevin** [comment]
> and also be consistent about Java7 or not, have the Java7 changes done on that issue and not on all issues currently pending

This does not make sense, new code should not introduce more work that needs to be changed later. 

> please provide the used codeformatting template in intellij somewhere

I need to look into this and will share my config.

**Comment by tubbynl** [comment]
dependencies between pieces of work should be at a minimum, doing re-work on parallel issues is a minor price to pay in order te reduce dependencies :)

**Comment by tubbynl** [comment]
i think the `.idea` directory is partially shared, some of it is in the `.gitignore` and some of it is already in git

**Comment by OGKevin** [comment]
> dependencies between pieces of work should be at a minimum, doing re-work on parallel issues is a minor price to pay in order te reduce dependencies :)

I think you're missing the point. Comparison, someone is cleaning your house and you know this is a work in progress. Why would you explicitly make the house more dirty so that the cleaning person has more stuff to clean and the progress takes longer. While you could help him/her by not explicitly make the house more dirty. Instead, you try to keep it as-is.

Same here, you know where are moving to java 7 compatibility why would you explicitly introduce in NEW code, java 8 only compatibility. This just introduces more work. Has nothing to do with dependency. Its just smart/logic thinking 🤔.

> I need to look into this and will share my config.
 

[settings.jar.zip](https://github.com/bunq/sdk_java/files/2118165/settings.jar.zip)

**Comment by tubbynl** [comment]
yes, but it's better applicable if the Java7 is already applied (a.k.a. restricted as compile target in build.gradle)

now it's an implicit restriction unclear for contributors, but temporarily until #42 is fixed :)

tnx for the settings 👍
